### ISSUE TITLE
Getting started link broken 

### ISSUE THREAD

**Issue by elvador** [lumail/lumail.org#10]
On https://lumail.org/:
* "Installagion & Usage" (typo)
* "Then read the _getting started guide_." links to https://lumail.org/**.**getting-started/ (notice the dot).

**Comment by skx** [comment]
This was fixed in bd968b626c29e28bab7ff4d6c69855bc659ef556 - I'm sorry I managed to forget to close the bug in the commit message.

Thanks for reporting it :)
